#!/usr/bin/env python3
"""
Convert OTA_SpriteV2.png sprite sheet into a C header with RGB565 PROGMEM arrays.

Sprite sheet layout:
  - 4 columns x 3 rows = 12 frames
  - 4px border between sprites, images go to the edge
  - Source sprite size: 378 x 274 px
  - Target output size: 200 x 145 px (scaled with Lanczos)
  
Colors are bitwise-inverted to match TFT_INVERSION_ON hardware setting.
Bytes are swapped for TFT_eSPI pushImage() (MSB first).
"""

from PIL import Image
import os
import sys

# Configuration
SPRITE_SHEET = os.path.join(os.path.dirname(__file__), "src", "OTA_SpriteV2.png")
OUTPUT_HEADER = os.path.join(os.path.dirname(__file__), "src", "ota_sprites.h")
COLS = 4
ROWS = 3
BORDER = 4  # pixels between sprites (verified by math: (1524 - 3*4) / 4 = 378)
TARGET_W = 200
TARGET_H = 145

def rgb_to_565(r, g, b):
    """Convert 8-bit RGB to 16-bit RGB565."""
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)

def swap_bytes(val16):
    """Swap bytes for TFT_eSPI (MSB first over SPI)."""
    return ((val16 & 0xFF) << 8) | ((val16 >> 8) & 0xFF)

def main():
    img = Image.open(SPRITE_SHEET).convert("RGB")
    total_w, total_h = img.size
    
    # Calculate individual sprite dimensions from the sheet
    sprite_w = (total_w - (COLS - 1) * BORDER) // COLS
    sprite_h = (total_h - (ROWS - 1) * BORDER) // ROWS
    print(f"Sheet size: {total_w}x{total_h}")
    print(f"Source sprite size: {sprite_w}x{sprite_h}")
    print(f"Target sprite size: {TARGET_W}x{TARGET_H}")
    
    sprites = []
    
    for row in range(ROWS):
        for col in range(COLS):
            x = col * (sprite_w + BORDER)
            y = row * (sprite_h + BORDER)
            
            # Extract sprite from sheet
            sprite = img.crop((x, y, x + sprite_w, y + sprite_h))
            
            # Scale down to target size with high-quality resampling
            sprite = sprite.resize((TARGET_W, TARGET_H), Image.LANCZOS)
            
            # Convert to RGB565 with inversion and byte-swap
            pixels = []
            for py in range(TARGET_H):
                for px in range(TARGET_W):
                    r, g, b = sprite.getpixel((px, py))
                    rgb565 = rgb_to_565(r, g, b)
                    # Bitwise invert for TFT_INVERSION_ON
                    rgb565 = (~rgb565) & 0xFFFF
                    # Byte-swap for SPI
                    rgb565 = swap_bytes(rgb565)
                    pixels.append(rgb565)
            
            sprites.append(pixels)
            idx = row * COLS + col
            print(f"  Frame {idx}: extracted from ({x},{y}), {len(pixels)} pixels")
    
    # Write C header
    with open(OUTPUT_HEADER, "w") as f:
        f.write("// Auto-generated by convert_sprites.py — DO NOT EDIT\n")
        f.write("// Source: OTA_SpriteV2.png (4x3 grid, 12 frames)\n")
        f.write("#pragma once\n")
        f.write("#include <pgmspace.h>\n\n")
        f.write(f"#define OTA_SPRITE_W {TARGET_W}\n")
        f.write(f"#define OTA_SPRITE_H {TARGET_H}\n")
        f.write(f"#define OTA_SPRITE_COUNT {COLS * ROWS}\n\n")
        
        for i, pixels in enumerate(sprites):
            f.write(f"static const uint16_t ota_sprite_{i}[{TARGET_W * TARGET_H}] PROGMEM = {{\n")
            for j in range(0, len(pixels), 16):
                line = ", ".join(f"0x{p:04X}" for p in pixels[j:j+16])
                f.write(f"  {line},\n")
            f.write("};\n\n")
        
        # Pointer array for indexed access
        f.write("static const uint16_t* const ota_sprites[OTA_SPRITE_COUNT] PROGMEM = {\n")
        for i in range(COLS * ROWS):
            f.write(f"  ota_sprite_{i},\n")
        f.write("};\n")
    
    file_size = os.path.getsize(OUTPUT_HEADER)
    print(f"\nGenerated {OUTPUT_HEADER}")
    print(f"Header file size: {file_size:,} bytes ({file_size/1024:.0f} KB)")
    print(f"Binary data per sprite: {TARGET_W * TARGET_H * 2:,} bytes")
    print(f"Total binary data: {COLS * ROWS * TARGET_W * TARGET_H * 2:,} bytes ({COLS * ROWS * TARGET_W * TARGET_H * 2 / 1024:.0f} KB)")

if __name__ == "__main__":
    main()
