#!/usr/bin/env python3
"""
Convert OTA_SpriteV2.png sprite sheet into a C header with JPEG PROGMEM arrays.

Sprite sheet layout:
  - 4 columns x 3 rows = 12 frames
  - 4px border between sprites
  - Target output size: 320 x 232 px (full screen width, keeping aspect ratio)
  
Colors are swapped (R <-> B) and inverted in Python so that the ESP32
can just decode the JPEG and push it directly to the display without
per-pixel processing overhead.
"""

from PIL import Image, ImageOps
import os
import io

# Configuration
SPRITE_SHEET = os.path.join(os.path.dirname(__file__), "src", "OTA_SpriteV3.png")
OUTPUT_HEADER = os.path.join(os.path.dirname(__file__), "src", "ota_sprites.h")
IMG_DIR = os.path.join(os.path.dirname(__file__), "src", "img")
COLS = 4
ROWS = 3
BORDER = 4
TARGET_W = 320
TARGET_H = 232
JPEG_QUALITY = 85

def main():
    if not os.path.exists(IMG_DIR):
        os.makedirs(IMG_DIR)

    img = Image.open(SPRITE_SHEET).convert("RGB")
    total_w, total_h = img.size
    
    sprite_w = (total_w - (COLS - 1) * BORDER) // COLS
    sprite_h = (total_h - (ROWS - 1) * BORDER) // ROWS
    print(f"Sheet size: {total_w}x{total_h}")
    print(f"Source sprite size: {sprite_w}x{sprite_h}")
    print(f"Target sprite size: {TARGET_W}x{TARGET_H}")
    
    jpeg_data_list = []
    
    for row in range(ROWS):
        for col in range(COLS):
            x = col * (sprite_w + BORDER)
            y = row * (sprite_h + BORDER)
            
            # Extract sprite from sheet
            sprite = img.crop((x, y, x + sprite_w, y + sprite_h))
            
            # Scale down to target size
            sprite = sprite.resize((TARGET_W, TARGET_H), Image.LANCZOS)
            
            # Swap R and B channels (for CYD display)
            r, g, b = sprite.split()
            sprite = Image.merge("RGB", (b, g, r))
            
            # Invert colors (for TFT_INVERSION_ON)
            sprite = ImageOps.invert(sprite)
            
            # Save to JPEG in img/ folder
            idx = row * COLS + col
            out_path = os.path.join(IMG_DIR, f"frame_{idx:02d}.jpg")
            sprite.save(out_path, format="JPEG", quality=JPEG_QUALITY)
            
            with open(out_path, "rb") as f:
                jpeg_bytes = f.read()
            jpeg_data_list.append(jpeg_bytes)
            
            print(f"  Frame {idx}: saved to {out_path} ({len(jpeg_bytes)} bytes)")
    
    # Write C header
    with open(OUTPUT_HEADER, "w") as f:
        f.write("// Auto-generated by convert_sprites.py — DO NOT EDIT\n")
        f.write("// Source: OTA_SpriteV3.png (4x3 grid, 12 frames)\n")
        f.write("#pragma once\n")
        f.write("#include <pgmspace.h>\n\n")
        f.write(f"#define OTA_SPRITE_W {TARGET_W}\n")
        f.write(f"#define OTA_SPRITE_H {TARGET_H}\n")
        f.write(f"#define OTA_SPRITE_COUNT {COLS * ROWS}\n\n")
        
        total_size = 0
        for i, data in enumerate(jpeg_data_list):
            total_size += len(data)
            f.write(f"const uint32_t ota_sprite_len_{i} = {len(data)};\n")
            f.write(f"const uint8_t ota_sprite_{i}[] PROGMEM = {{\n")
            for j in range(0, len(data), 16):
                line = ", ".join(f"0x{b:02X}" for b in data[j:j+16])
                f.write(f"  {line},\n")
            f.write("};\n\n")
        
        # Pointer arrays for indexed access
        f.write("const uint8_t* const ota_sprites[OTA_SPRITE_COUNT] PROGMEM = {\n")
        for i in range(COLS * ROWS):
            f.write(f"  ota_sprite_{i},\n")
        f.write("};\n\n")
        
        f.write("const uint32_t ota_sprite_lens[OTA_SPRITE_COUNT] = {\n")
        for i in range(COLS * ROWS):
            f.write(f"  ota_sprite_len_{i},\n")
        f.write("};\n\n")
        
        # Add special boot sprites for frames 4, 8, 11 (scaled to 200x145)
        boot_frames = [4, 8, 11]
        for i, f_idx in enumerate(boot_frames):
            row = f_idx // COLS
            col = f_idx % COLS
            x = col * (sprite_w + BORDER)
            y = row * (sprite_h + BORDER)
            
            boot_sprite = img.crop((x, y, x + sprite_w, y + sprite_h))
            boot_sprite = boot_sprite.resize((200, 145), Image.LANCZOS)
            r, g, b = boot_sprite.split()
            boot_sprite = Image.merge("RGB", (b, g, r))
            boot_sprite = ImageOps.invert(boot_sprite)
            
            boot_path = os.path.join(IMG_DIR, f"boot_{i}.jpg")
            boot_sprite.save(boot_path, format="JPEG", quality=JPEG_QUALITY)
            
            with open(boot_path, "rb") as f_boot:
                boot_bytes = f_boot.read()
            
            f.write(f"// Special boot sprite {i} (frame {f_idx}, 200x145)\n")
            f.write(f"const uint32_t ota_sprite_boot_len_{i} = {len(boot_bytes)};\n")
            f.write(f"const uint8_t ota_sprite_boot_{i}[] PROGMEM = {{\n")
            for j in range(0, len(boot_bytes), 16):
                line = ", ".join(f"0x{b:02X}" for b in boot_bytes[j:j+16])
                f.write(f"  {line},\n")
            f.write("};\n\n")
    
    print(f"\nGenerated {OUTPUT_HEADER}")
    print(f"Total JPEG binary data: {total_size:,} bytes ({total_size / 1024:.0f} KB)")

if __name__ == "__main__":
    main()
