[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = min_spiffs.csv
monitor_speed = 115200

; --- Upload Method ---
; USB upload (comment the two lines below to fall back to USB)
upload_protocol = espota
upload_port = peachpulp.local

build_flags = -Isrc -Isrc/drivers

lib_deps =
    janelia-arduino/TMC2209 @ 10.1.1
    olikraus/U8g2 @ ^2.34.22
    ; adafruit/Adafruit seesaw Library @ ^1.7.9 ; added in Milestone 3 (encoders)
