[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; --- Upload Method ---
; USB upload (Default - active when OTA is commented out)
; PlatformIO automatically detects the serial port.

; OTA upload (Uncomment these lines to upload over WiFi once connected to sdsmtopn)
; upload_protocol = espota
; upload_port = peachpulp.local
; upload_port = 192.168.4.1